service: apollo-lambda
provider:
  name: aws
  runtime: nodejs6.10
  region: ap-southeast-2
  stage: development
  timeout: 15
  environment:
    MONGO_HOST: ${env:MONGO_HOST}
    MONGO_PORT: 27017
    MONGO_NAME: posts

functions:
  graphql:
    handler: handler.graphql
    vpc:
      securityGroupIds:
        # - 'Fn::ImportValue': '${env:VPC_STAGE}-lambda-sg'
        - sg-2a1f364d
        - sg-0c11386b
      subnetIds:
        - subnet-e8633d9e
        - subnet-826df7db
        # - 'Fn::ImportValue': '${env:VPC_STAGE}-subnet-a-private'
        # - 'Fn::ImportValue': '${env:VPC_STAGE}-subnet-b-private'
    events:
      - http:
          path: graphql
          method: post
          cors: true

  graphiql:
    handler: handler.graphiql
    events:
      - http:
          path: graphiql
          method: get

  hello:
    handler: handler.hello
